projects:
  NvN League:
    schemaPath: src/graphql/schema.json
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-west-2
        apiId: lwuv4qj3fjejhc3qzc45e2dzma
        maxDepth: 2
extensions:
  amplify:
    version: 3
